package db;
// Generated Apr 16, 2019 6:39:02 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AdminLog generated by hbm2java
 */
public class AdminLog  implements java.io.Serializable {


     private int idLog;
     private String tekst;
     private Date datum;

    public AdminLog() {
    }

    public AdminLog(int idLog, String tekst, Date datum) {
       this.idLog = idLog;
       this.tekst = tekst;
       this.datum = datum;
    }
   
    public int getIdLog() {
        return this.idLog;
    }
    
    public void setIdLog(int idLog) {
        this.idLog = idLog;
    }
    public String getTekst() {
        return this.tekst;
    }
    
    public void setTekst(String tekst) {
        this.tekst = tekst;
    }
    public Date getDatum() {
        return this.datum;
    }
    
    public void setDatum(Date datum) {
        this.datum = datum;
    }




}


