package db;
// Generated Apr 17, 2019 7:40:18 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ankete generated by hbm2java
 */
public class Ankete  implements java.io.Serializable {


     private int idAnketa;
     private String kreator;
     private String naziv;
     private int nivoVidljivosti;
     private Set pitanjas = new HashSet(0);

    public Ankete() {
    }

	
    public Ankete(int idAnketa, String kreator, String naziv, int nivoVidljivosti) {
        this.idAnketa = idAnketa;
        this.kreator = kreator;
        this.naziv = naziv;
        this.nivoVidljivosti = nivoVidljivosti;
    }
    public Ankete(int idAnketa, String kreator, String naziv, int nivoVidljivosti, Set pitanjas) {
       this.idAnketa = idAnketa;
       this.kreator = kreator;
       this.naziv = naziv;
       this.nivoVidljivosti = nivoVidljivosti;
       this.pitanjas = pitanjas;
    }
   
    public int getIdAnketa() {
        return this.idAnketa;
    }
    
    public void setIdAnketa(int idAnketa) {
        this.idAnketa = idAnketa;
    }
    public String getKreator() {
        return this.kreator;
    }
    
    public void setKreator(String kreator) {
        this.kreator = kreator;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public int getNivoVidljivosti() {
        return this.nivoVidljivosti;
    }
    
    public void setNivoVidljivosti(int nivoVidljivosti) {
        this.nivoVidljivosti = nivoVidljivosti;
    }
    public Set getPitanjas() {
        return this.pitanjas;
    }
    
    public void setPitanjas(Set pitanjas) {
        this.pitanjas = pitanjas;
    }




}


