package db;
// Generated Jan 31, 2019 12:14:21 AM by Hibernate Tools 4.3.1

/**
 * KarakteristikeProstora generated by hbm2java
 */
public class KarakteristikeProstora implements java.io.Serializable {

    private int idKarakteristika;
    private Dogadjaji dogadjaji;
    private StavkeSifarnika stavkeSifarnika;

    public KarakteristikeProstora() {
    }

    public KarakteristikeProstora(int idKarakteristika, Dogadjaji dogadjaji, StavkeSifarnika stavkeSifarnika) {
        this.idKarakteristika = idKarakteristika;
        this.dogadjaji = dogadjaji;
        this.stavkeSifarnika = stavkeSifarnika;
    }

    public int getIdKarakteristika() {
        return this.idKarakteristika;
    }

    public void setIdKarakteristika(int idKarakteristika) {
        this.idKarakteristika = idKarakteristika;
    }

    public Dogadjaji getDogadjaji() {
        return this.dogadjaji;
    }

    public void setDogadjaji(Dogadjaji dogadjaji) {
        this.dogadjaji = dogadjaji;
    }

    public StavkeSifarnika getStavkeSifarnika() {
        return this.stavkeSifarnika;
    }

    public void setStavkeSifarnika(StavkeSifarnika stavkeSifarnika) {
        this.stavkeSifarnika = stavkeSifarnika;
    }

}
