package db;
// Generated Nov 24, 2018 6:36:55 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Korisnici generated by hbm2java
 */
public class Korisnici  implements java.io.Serializable {


     private String korisnickoIme;
     private String lozinka;
     private int tip;
     private Set vestis = new HashSet(0);

    public Korisnici() {
    }

	
    public Korisnici(String korisnickoIme, String lozinka, int tip) {
        this.korisnickoIme = korisnickoIme;
        this.lozinka = lozinka;
        this.tip = tip;
    }
    public Korisnici(String korisnickoIme, String lozinka, int tip, Set vestis) {
       this.korisnickoIme = korisnickoIme;
       this.lozinka = lozinka;
       this.tip = tip;
       this.vestis = vestis;
    }
   
    public String getKorisnickoIme() {
        return this.korisnickoIme;
    }
    
    public void setKorisnickoIme(String korisnickoIme) {
        this.korisnickoIme = korisnickoIme;
    }
    public String getLozinka() {
        return this.lozinka;
    }
    
    public void setLozinka(String lozinka) {
        this.lozinka = lozinka;
    }
    public int getTip() {
        return this.tip;
    }
    
    public void setTip(int tip) {
        this.tip = tip;
    }
    public Set getVestis() {
        return this.vestis;
    }
    
    public void setVestis(Set vestis) {
        this.vestis = vestis;
    }




}


