package db;
// Generated Apr 21, 2019 2:57:51 PM by Hibernate Tools 4.3.1



/**
 * Odgovori generated by hbm2java
 */
public class Odgovori  implements java.io.Serializable {


     private int idOdgovor;
     private PonudjeniOdgovori ponudjeniOdgovori;
     private PopunjeneAnkete popunjeneAnkete;

    public Odgovori() {
    }

    public Odgovori(int idOdgovor, PonudjeniOdgovori ponudjeniOdgovori, PopunjeneAnkete popunjeneAnkete) {
       this.idOdgovor = idOdgovor;
       this.ponudjeniOdgovori = ponudjeniOdgovori;
       this.popunjeneAnkete = popunjeneAnkete;
    }
   
    public int getIdOdgovor() {
        return this.idOdgovor;
    }
    
    public void setIdOdgovor(int idOdgovor) {
        this.idOdgovor = idOdgovor;
    }
    public PonudjeniOdgovori getPonudjeniOdgovori() {
        return this.ponudjeniOdgovori;
    }
    
    public void setPonudjeniOdgovori(PonudjeniOdgovori ponudjeniOdgovori) {
        this.ponudjeniOdgovori = ponudjeniOdgovori;
    }
    public PopunjeneAnkete getPopunjeneAnkete() {
        return this.popunjeneAnkete;
    }
    
    public void setPopunjeneAnkete(PopunjeneAnkete popunjeneAnkete) {
        this.popunjeneAnkete = popunjeneAnkete;
    }




}


