package db;
// Generated Jan 22, 2019 5:01:43 PM by Hibernate Tools 4.3.1


import java.util.Date;
import org.jsoup.Jsoup;

/**
 * Oglasi generated by hbm2java
 */
public class Oglasi  implements java.io.Serializable {


     private int idOglas;
     private Korisnici korisnici;
     private String naslov;
     private String tekst;
     private Date datumKreiranja;
     private Date datumIsticanja;
     
     private String arhiviran = "";

    public Oglasi() {
    }

    public Oglasi(int idOglas, Korisnici korisnici, String naslov, String tekst, Date datumKreiranja, Date datumIsticanja) {
       this.idOglas = idOglas;
       this.korisnici = korisnici;
       this.naslov = naslov;
       this.tekst = tekst;
       this.datumKreiranja = datumKreiranja;
       this.datumIsticanja = datumIsticanja;
    }
   
    public int getIdOglas() {
        return this.idOglas;
    }
    
    public void setIdOglas(int idOglas) {
        this.idOglas = idOglas;
    }
    public Korisnici getKorisnici() {
        return this.korisnici;
    }
    
    public void setKorisnici(Korisnici korisnici) {
        this.korisnici = korisnici;
    }
    public String getNaslov() {
        return this.naslov;
    }
    
    public void setNaslov(String naslov) {
        this.naslov = naslov;
    }
    public String getTekst() {
        return this.tekst;
    }
    
    public void setTekst(String tekst) {
        this.tekst = tekst;
    }
    public Date getDatumKreiranja() {
        return this.datumKreiranja;
    }
    
    public void setDatumKreiranja(Date datumKreiranja) {
        this.datumKreiranja = datumKreiranja;
    }
    public Date getDatumIsticanja() {
        return this.datumIsticanja;
    }
    
    public void setDatumIsticanja(Date datumIsticanja) {
        this.datumIsticanja = datumIsticanja;
    }
    
    public String getNaslovShort() {
        if (naslov.length() <= 40)
            return naslov;
        else 
            return naslov.substring(0, Math.min(naslov.length(), 40))+"...";
    }
    
    public String getTekstShort() {
        String tekstShort = Jsoup.parse(tekst).text();
        return tekstShort.substring(0, Math.min(tekstShort.length(), 150))+"...";
    }
    
    public String getTekstShortRezultatPretrage() {
        String tekstShort = Jsoup.parse(tekst).text();
        return tekstShort.substring(0, Math.min(tekstShort.length(), 256))+"...";
    }
    
    public void setArhiviran(String arhiviran) {
        this.arhiviran = arhiviran;
    }
    
    public String getArhiviran() {
        Date danas = new Date();
        if (danas.after(datumIsticanja)) {
            arhiviran = "expired";
        }
        return arhiviran;
    }
    
}


