package db;
// Generated Jan 22, 2019 5:01:43 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Oglasi generated by hbm2java
 */
public class Oglasi  implements java.io.Serializable {


     private int idOglas;
     private Korisnici korisnici;
     private String naslov;
     private String tekst;
     private Date datumKreiranja;
     private Date datumIsticanja;

    public Oglasi() {
    }

    public Oglasi(int idOglas, Korisnici korisnici, String naslov, String tekst, Date datumKreiranja, Date datumIsticanja) {
       this.idOglas = idOglas;
       this.korisnici = korisnici;
       this.naslov = naslov;
       this.tekst = tekst;
       this.datumKreiranja = datumKreiranja;
       this.datumIsticanja = datumIsticanja;
    }
   
    public int getIdOglas() {
        return this.idOglas;
    }
    
    public void setIdOglas(int idOglas) {
        this.idOglas = idOglas;
    }
    public Korisnici getKorisnici() {
        return this.korisnici;
    }
    
    public void setKorisnici(Korisnici korisnici) {
        this.korisnici = korisnici;
    }
    public String getNaslov() {
        return this.naslov;
    }
    
    public void setNaslov(String naslov) {
        this.naslov = naslov;
    }
    public String getTekst() {
        return this.tekst;
    }
    
    public void setTekst(String tekst) {
        this.tekst = tekst;
    }
    public Date getDatumKreiranja() {
        return this.datumKreiranja;
    }
    
    public void setDatumKreiranja(Date datumKreiranja) {
        this.datumKreiranja = datumKreiranja;
    }
    public Date getDatumIsticanja() {
        return this.datumIsticanja;
    }
    
    public void setDatumIsticanja(Date datumIsticanja) {
        this.datumIsticanja = datumIsticanja;
    }
    
}


