package db;
// Generated Apr 17, 2019 7:40:18 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Pitanja generated by hbm2java
 */
public class Pitanja  implements java.io.Serializable {


     private int idPitanje;
     private Ankete ankete;
     private String pitanje;
     private int tip;
     private Set ponudjeniOdgovoris = new HashSet(0);
     
     private List<PonudjeniOdgovori> ponudjeniOdgovori;

    public Pitanja() {
    }

	
    public Pitanja(int idPitanje, Ankete ankete, String pitanje, int tip) {
        this.idPitanje = idPitanje;
        this.ankete = ankete;
        this.pitanje = pitanje;
        this.tip = tip;
    }
    public Pitanja(int idPitanje, Ankete ankete, String pitanje, int tip, Set ponudjeniOdgovoris) {
       this.idPitanje = idPitanje;
       this.ankete = ankete;
       this.pitanje = pitanje;
       this.tip = tip;
       this.ponudjeniOdgovoris = ponudjeniOdgovoris;
    }
   
    public int getIdPitanje() {
        return this.idPitanje;
    }
    
    public void setIdPitanje(int idPitanje) {
        this.idPitanje = idPitanje;
    }
    public Ankete getAnkete() {
        return this.ankete;
    }
    
    public void setAnkete(Ankete ankete) {
        this.ankete = ankete;
    }
    public String getPitanje() {
        return this.pitanje;
    }
    
    public void setPitanje(String pitanje) {
        this.pitanje = pitanje;
    }
    public int getTip() {
        return this.tip;
    }
    
    public void setTip(int tip) {
        this.tip = tip;
    }
    public Set getPonudjeniOdgovoris() {
        return this.ponudjeniOdgovoris;
    }
    
    public void setPonudjeniOdgovoris(Set ponudjeniOdgovoris) {
        this.ponudjeniOdgovoris = ponudjeniOdgovoris;
    }

    public List<PonudjeniOdgovori> getPonudjeniOdgovori() {
        return ponudjeniOdgovori;
    }

    public void setPonudjeniOdgovori(List<PonudjeniOdgovori> ponudjeniOdgovori) {
        this.ponudjeniOdgovori = ponudjeniOdgovori;
    }




}


