package db;
// Generated Apr 21, 2019 2:57:51 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PopunjeneAnkete generated by hbm2java
 */
public class PopunjeneAnkete  implements java.io.Serializable {


     private int idPopunjenaAnketa;
     private Ankete ankete;
     private Korisnici korisnici;
     private String cookie;
     private Date datum;
     private Set odgovoris = new HashSet(0);

    public PopunjeneAnkete() {
    }

	
    public PopunjeneAnkete(int idPopunjenaAnketa, Ankete ankete, Date datum) {
        this.idPopunjenaAnketa = idPopunjenaAnketa;
        this.ankete = ankete;
        this.datum = datum;
    }
    public PopunjeneAnkete(int idPopunjenaAnketa, Ankete ankete, Date datum, Korisnici korisnici, String cookie, Set odgovoris) {
       this.idPopunjenaAnketa = idPopunjenaAnketa;
       this.ankete = ankete;
       this.korisnici = korisnici;
       this.cookie = cookie;
       this.odgovoris = odgovoris;
       this.datum = datum;
    }
   
    public int getIdPopunjenaAnketa() {
        return this.idPopunjenaAnketa;
    }
    
    public void setIdPopunjenaAnketa(int idPopunjenaAnketa) {
        this.idPopunjenaAnketa = idPopunjenaAnketa;
    }
    public Ankete getAnkete() {
        return this.ankete;
    }
    
    public void setAnkete(Ankete ankete) {
        this.ankete = ankete;
    }
    public Korisnici getKorisnici() {
        return this.korisnici;
    }
    
    public void setKorisnici(Korisnici korisnici) {
        this.korisnici = korisnici;
    }
    public String getCookie() {
        return this.cookie;
    }
    
    public void setCookie(String cookie) {
        this.cookie = cookie;
    }
    public Set getOdgovoris() {
        return this.odgovoris;
    }
    
    public void setOdgovoris(Set odgovoris) {
        this.odgovoris = odgovoris;
    }

    public Date getDatum() {
        return datum;
    }

    public void setDatum(Date datum) {
        this.datum = datum;
    }

}


