package db;
// Generated Apr 16, 2019 4:40:41 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SifarniciIzvestaj generated by hbm2java
 */
public class SifarniciIzvestaj  implements java.io.Serializable {


     private int idSifarnik;
     private String naziv;
     private Set stavkeIzvestajs = new HashSet(0);

    public SifarniciIzvestaj() {
    }

	
    public SifarniciIzvestaj(int idSifarnik, String naziv) {
        this.idSifarnik = idSifarnik;
        this.naziv = naziv;
    }
    public SifarniciIzvestaj(int idSifarnik, String naziv, Set stavkeIzvestajs) {
       this.idSifarnik = idSifarnik;
       this.naziv = naziv;
       this.stavkeIzvestajs = stavkeIzvestajs;
    }
   
    public int getIdSifarnik() {
        return this.idSifarnik;
    }
    
    public void setIdSifarnik(int idSifarnik) {
        this.idSifarnik = idSifarnik;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public Set getStavkeIzvestajs() {
        return this.stavkeIzvestajs;
    }
    
    public void setStavkeIzvestajs(Set stavkeIzvestajs) {
        this.stavkeIzvestajs = stavkeIzvestajs;
    }




}


