package db;
// Generated Nov 24, 2018 6:36:55 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sifarnici generated by hbm2java
 */
public class Sifarnici  implements java.io.Serializable {


     private int idSifarnik;
     private String naziv;
     private Set stavkeSifarnikas = new HashSet(0);

    public Sifarnici() {
    }

	
    public Sifarnici(int idSifarnik, String naziv) {
        this.idSifarnik = idSifarnik;
        this.naziv = naziv;
    }
    public Sifarnici(int idSifarnik, String naziv, Set stavkeSifarnikas) {
       this.idSifarnik = idSifarnik;
       this.naziv = naziv;
       this.stavkeSifarnikas = stavkeSifarnikas;
    }
   
    public int getIdSifarnik() {
        return this.idSifarnik;
    }
    
    public void setIdSifarnik(int idSifarnik) {
        this.idSifarnik = idSifarnik;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public Set getStavkeSifarnikas() {
        return this.stavkeSifarnikas;
    }
    
    public void setStavkeSifarnikas(Set stavkeSifarnikas) {
        this.stavkeSifarnikas = stavkeSifarnikas;
    }




}


