package db;
// Generated Apr 16, 2019 4:40:41 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * StavkeIzvestaj generated by hbm2java
 */
public class StavkeIzvestaj  implements java.io.Serializable {


     private int idStavka;
     private SifarniciIzvestaj sifarniciIzvestaj;
     private String naziv;
     private Date datum;

    public StavkeIzvestaj() {
    }

    public StavkeIzvestaj(int idStavka, SifarniciIzvestaj sifarniciIzvestaj, String naziv, Date datum) {
       this.idStavka = idStavka;
       this.sifarniciIzvestaj = sifarniciIzvestaj;
       this.naziv = naziv;
       this.datum = datum;
    }
   
    public int getIdStavka() {
        return this.idStavka;
    }
    
    public void setIdStavka(int idStavka) {
        this.idStavka = idStavka;
    }
    public SifarniciIzvestaj getSifarniciIzvestaj() {
        return this.sifarniciIzvestaj;
    }
    
    public void setSifarniciIzvestaj(SifarniciIzvestaj sifarniciIzvestaj) {
        this.sifarniciIzvestaj = sifarniciIzvestaj;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public Date getDatum() {
        return this.datum;
    }
    
    public void setDatum(Date datum) {
        this.datum = datum;
    }




}


