package db;
// Generated Nov 24, 2018 6:36:55 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Vesti generated by hbm2java
 */
public class Vesti implements java.io.Serializable {

    private int idVest;
    private Korisnici korisnici;
    private String naslov;
    private String tekst;
    private StavkeSifarnika kategorija;
    private Date datum;
    private String thumbnail;
    private int arhivirana;

    public Vesti() {
    }

    public Vesti(int idVest, Korisnici korisnici, String naslov, String tekst, StavkeSifarnika kategorija, Date datum, String thumbnail, int arhivirana) {
        this.idVest = idVest;
        this.korisnici = korisnici;
        this.naslov = naslov;
        this.tekst = tekst;
        this.kategorija = kategorija;
        this.datum = datum;
        
        this.thumbnail = thumbnail;
        this.arhivirana = arhivirana;
    }

    public int getIdVest() {
        return this.idVest;
    }

    public void setIdVest(int idVest) {
        this.idVest = idVest;
    }

    public Korisnici getKorisnici() {
        return this.korisnici;
    }

    public void setKorisnici(Korisnici korisnici) {
        this.korisnici = korisnici;
    }

    public String getNaslov() {
        return this.naslov;
    }

    public void setNaslov(String naslov) {
        this.naslov = naslov;
    }

    public String getTekst() {
        return this.tekst;
    }

    public void setTekst(String tekst) {
        this.tekst = tekst;
    }

    public StavkeSifarnika getKategorija() {
        return this.kategorija;
    }

    public void setKategorija(StavkeSifarnika kategorija) {
        this.kategorija = kategorija;
    }

    public Date getDatum() {
        return this.datum;
    }

    public void setDatum(Date datum) {
        this.datum = datum;
    }

    public String getTekstShort() {
        return tekst.substring(0, Math.min(tekst.length(), 100))+"...";
    }
    
    public String getNaslovShort() {
        if (naslov.length() <= 40)
            return naslov;
        else 
            return naslov.substring(0, Math.min(naslov.length(), 40))+"...";
    }
    
    public String getThumbnail() {
        return thumbnail;
    }
    
    public void setThumbnail(String thumbnail) {
        this.thumbnail = thumbnail;
    }
    
    public String getThumbnailUrl() {
        return "img:thumbnails/" + thumbnail;
    }
    
    public String getThumbnailUrlBootsfaces() {
        return "resources/img/thumbnails/" + thumbnail;
    }
    
    public int getArhivirana() {
        return arhivirana;
    }
    
    public void setArhivirana(int arhivirana) {
        this.arhivirana = arhivirana;
    }

}
