package db;
// Generated Apr 29, 2019 10:11:57 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ZaboravljeneLozinke generated by hbm2java
 */
public class ZaboravljeneLozinke  implements java.io.Serializable {


     private String korisnickoIme;
     private Korisnici korisnici;
     private Date datum;
     private byte[] novaLozinka;
     private byte[] salt;

    public ZaboravljeneLozinke() {
    }

    public ZaboravljeneLozinke(Korisnici korisnici, Date datum, byte[] novaLozinka, byte[] salt) {
       this.korisnici = korisnici;
       this.datum = datum;
       this.novaLozinka = novaLozinka;
       this.salt = salt;
    }
   
    public String getKorisnickoIme() {
        return this.korisnickoIme;
    }
    
    public void setKorisnickoIme(String korisnickoIme) {
        this.korisnickoIme = korisnickoIme;
    }
    public Korisnici getKorisnici() {
        return this.korisnici;
    }
    
    public void setKorisnici(Korisnici korisnici) {
        this.korisnici = korisnici;
    }
    public Date getDatum() {
        return this.datum;
    }
    
    public void setDatum(Date datum) {
        this.datum = datum;
    }

    public byte[] getNovaLozinka() {
        return novaLozinka;
    }

    public void setNovaLozinka(byte[] novaLozinka) {
        this.novaLozinka = novaLozinka;
    }

    public byte[] getSalt() {
        return salt;
    }

    public void setSalt(byte[] salt) {
        this.salt = salt;
    }

}


